apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: rajeevmagar/all-in-one:v1.0.4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-app
spec:
  selector:
    app.kubernetes.io/name: python-flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  type: LoadBalancer