pipeline {
    agent any
    environment {
        IMG_NAME = "rajeevmagar/all-in-one" // Username and Repo of the Dockerhub.
        IMG_TAG = "v1.0.${BUILD_NUMBER}" // Gives Image Tag Number.
        DOCKERFILE_PATH = "python-flask-app/Dockerfile" // Dockerfile location.
        DOCKERHUB_CREDENTIALS = "docker-hub-credentials" // Dockerhub Credentials stored in the Jenkins.
    }
    stages {
        stage('Build') {
            steps {
                script {
                    // Build the Docker Image.
                    customImg = docker.build("${IMG_NAME}:${IMG_TAG}", "--file ${DOCKERFILE_PATH} .")
                }
            }
        }
        stage('Push to Dockerhub') {
            steps {
                script {
                    // Push the Docker Image to Dockerhub.
                    docker.withRegistry('', "${DOCKERHUB_CREDENTIALS}") {
                        customImg.push()
                    }
                }
            }
        }
        stage('Cleaning up the Local Image'){
            steps {
                script {
                    // Remove the Docker Image from Local.
                    docker.image("${IMG_NAME}:${IMG_TAG}").remove()
                }
            }
        }
    }
}