pipeline {
    agent any
    environment {
        IMG_NAME = "rajeevmagar/all-in-one" // Username and Repo of the Dockerhub.
        IMG_TAG = "v1.0.${BUILD_NUMBER}" // Gives Image Tag Number.
        DOCKERFILE_PATH = "python-flask-app/Dockerfile" // Dockerfile location.
        DOCKERHUB_CREDENTIALS = "docker-hub-credentials" // Dockerhub Credentials stored in the Jenkins.
        K8S_MANIFEST_PATH = "python-flask-app/k8s/deploy.yaml" // Location of k8s file.
    }
    stages {
        stage('Build') {
            steps {
                script {
                    // Build the Docker Image.
                    customImg = docker.build("${IMG_NAME}:${IMG_TAG}", "--file ${DOCKERFILE_PATH} .")
                }
            }
        }
        stage('Push to Dockerhub') {
            steps {
                script {
                    // Push the Docker Image to Dockerhub.
                    docker.withRegistry('', "${DOCKERHUB_CREDENTIALS}") {
                        customImg.push()
                    }
                }
            }
        }
        stage('Cleaning up the Local Image'){
            steps {
             // Delete the Local Image.
                sh "docker rmi ${IMG_NAME}:${IMG_TAG}"
            }
        }
        stage('Update k8s Manifest'){
            steps {
                script {
                    // Update the k8s Manifest.
                    sh """
                        cat ${K8S_MANIFEST_PATH}
                        sed -i 's|image: ${IMG_NAME}:.*\$|image: ${IMG_NAME}:${IMG_TAG}|' ${K8S_MANIFEST_PATH}
                        cat ${K8S_MANIFEST_PATH}
                    """
                    // Commit the changes to the k8s Manifest.
                    sshagent(credentials:['4b2106fc-c96a-489d-b8a7-9dc887caf143']){
                        sh """
                            git add ${K8S_MANIFEST_PATH}
                            git commit -m "Update image in kubernetes manifest | Jenkins Pipeline"
                            git push git@github.com:RajeevThapa/all-in-one.git HEAD:main
                        """
                    }
                }
            }
        }
    }
}